namespace Seprise
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            panelHeader = new Panel();
            lblTitulo = new Label();
            panelContenido = new Panel();
            lblSeccionComun = new Label();
            btnPacientes = new Button();
            lblSeccionConsultorios = new Label();
            btnGestionMedicos = new Button();
            btnGestionAgenda = new Button();
            btnGestionTurnos = new Button();
            btnRecepcionarPaciente = new Button();
            btnAtencionPaciente = new Button();
            lblSeccionEstudios = new Label();
            btnGestionAgendaEstudios = new Button();
            btnGestionTurnosEstudios = new Button();
            btnRecepcionarPacienteEstudio = new Button();
            btnSolicitudEstudios = new Button();
            btnConfirmacionEstudios = new Button();
            btnProcesamientoEstudios = new Button();
            panelHeader.SuspendLayout();
            panelContenido.SuspendLayout();
            SuspendLayout();
            panelHeader.BackColor = Color.FromArgb(0, 150, 136);
            panelHeader.Controls.Add(lblTitulo);
            panelHeader.Dock = DockStyle.Top;
            panelHeader.Location = new Point(0, 0);
            panelHeader.Name = "panelHeader";
            panelHeader.Size = new Size(1254, 80);
            panelHeader.TabIndex = 0;
            lblTitulo.Dock = DockStyle.Fill;
            lblTitulo.Font = new Font("Segoe UI", 20F, FontStyle.Bold);
            lblTitulo.ForeColor = Color.White;
            lblTitulo.Location = new Point(0, 0);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(1254, 80);
            lblTitulo.TabIndex = 0;
            lblTitulo.Text = "Sistema de Gestión - Clínica SEPRISE";
            lblTitulo.TextAlign = ContentAlignment.MiddleCenter;
            panelContenido.AutoScroll = true;
            panelContenido.BackColor = Color.White;
            panelContenido.Controls.Add(lblSeccionComun);
            panelContenido.Controls.Add(btnPacientes);
            panelContenido.Controls.Add(lblSeccionConsultorios);
            panelContenido.Controls.Add(btnGestionMedicos);
            panelContenido.Controls.Add(btnGestionAgenda);
            panelContenido.Controls.Add(btnGestionTurnos);
            panelContenido.Controls.Add(btnRecepcionarPaciente);
            panelContenido.Controls.Add(btnAtencionPaciente);
            panelContenido.Controls.Add(lblSeccionEstudios);
            panelContenido.Controls.Add(btnGestionAgendaEstudios);
            panelContenido.Controls.Add(btnGestionTurnosEstudios);
            panelContenido.Controls.Add(btnRecepcionarPacienteEstudio);
            panelContenido.Controls.Add(btnSolicitudEstudios);
            panelContenido.Controls.Add(btnConfirmacionEstudios);
            panelContenido.Controls.Add(btnProcesamientoEstudios);
            panelContenido.Dock = DockStyle.Fill;
            panelContenido.Location = new Point(0, 80);
            panelContenido.Name = "panelContenido";
            panelContenido.Size = new Size(1254, 623);
            panelContenido.TabIndex = 1;
            panelContenido.Paint += panelContenido_Paint;
            lblSeccionComun.BackColor = Color.FromArgb(0, 150, 136);
            lblSeccionComun.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblSeccionComun.ForeColor = Color.White;
            lblSeccionComun.Location = new Point(30, 20);
            lblSeccionComun.Name = "lblSeccionComun";
            lblSeccionComun.Padding = new Padding(20, 0, 0, 0);
            lblSeccionComun.Size = new Size(1203, 40);
            lblSeccionComun.TabIndex = 0;
            lblSeccionComun.Text = "ADMINISTRACIÓN";
            lblSeccionComun.TextAlign = ContentAlignment.MiddleLeft;
            lblSeccionComun.Click += lblSeccionComun_Click;
            btnPacientes.BackColor = Color.FromArgb(178, 235, 242);
            btnPacientes.Cursor = Cursors.Hand;
            btnPacientes.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnPacientes.FlatAppearance.BorderSize = 2;
            btnPacientes.FlatStyle = FlatStyle.Flat;
            btnPacientes.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnPacientes.Location = new Point(250, 80);
            btnPacientes.Name = "btnPacientes";
            btnPacientes.Size = new Size(180, 120);
            btnPacientes.TabIndex = 2;
            btnPacientes.Text = "👥\r\n\r\nGestión de\r\nPacientes";
            btnPacientes.UseVisualStyleBackColor = false;
            btnPacientes.Click += btnPacientes_Click;
            lblSeccionConsultorios.BackColor = Color.FromArgb(0, 150, 136);
            lblSeccionConsultorios.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblSeccionConsultorios.ForeColor = Color.White;
            lblSeccionConsultorios.Location = new Point(30, 230);
            lblSeccionConsultorios.Name = "lblSeccionConsultorios";
            lblSeccionConsultorios.Padding = new Padding(20, 0, 0, 0);
            lblSeccionConsultorios.Size = new Size(1203, 40);
            lblSeccionConsultorios.TabIndex = 3;
            lblSeccionConsultorios.Text = "CONSULTORIOS EXTERNOS";
            lblSeccionConsultorios.TextAlign = ContentAlignment.MiddleLeft;
            btnGestionMedicos.BackColor = Color.FromArgb(178, 235, 242);
            btnGestionMedicos.Cursor = Cursors.Hand;
            btnGestionMedicos.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnGestionMedicos.FlatAppearance.BorderSize = 2;
            btnGestionMedicos.FlatStyle = FlatStyle.Flat;
            btnGestionMedicos.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnGestionMedicos.Location = new Point(50, 80);
            btnGestionMedicos.Name = "btnGestionMedicos";
            btnGestionMedicos.Size = new Size(180, 120);
            btnGestionMedicos.TabIndex = 1;
            btnGestionMedicos.Text = "👨‍⚕️\r\n\r\nGestión de\r\nMédicos";
            btnGestionMedicos.UseVisualStyleBackColor = false;
            btnGestionMedicos.Click += btnGestionMedicos_Click;
            btnGestionAgenda.BackColor = Color.FromArgb(178, 235, 242);
            btnGestionAgenda.Cursor = Cursors.Hand;
            btnGestionAgenda.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnGestionAgenda.FlatAppearance.BorderSize = 2;
            btnGestionAgenda.FlatStyle = FlatStyle.Flat;
            btnGestionAgenda.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnGestionAgenda.Location = new Point(50, 292);
            btnGestionAgenda.Name = "btnGestionAgenda";
            btnGestionAgenda.Size = new Size(180, 120);
            btnGestionAgenda.TabIndex = 5;
            btnGestionAgenda.Text = "📅\n\nGestión de Agenda\n";
            btnGestionAgenda.UseVisualStyleBackColor = false;
            btnGestionAgenda.Click += btnGestionAgenda_Click;
            btnGestionTurnos.BackColor = Color.FromArgb(178, 235, 242);
            btnGestionTurnos.Cursor = Cursors.Hand;
            btnGestionTurnos.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnGestionTurnos.FlatAppearance.BorderSize = 2;
            btnGestionTurnos.FlatStyle = FlatStyle.Flat;
            btnGestionTurnos.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnGestionTurnos.Location = new Point(250, 292);
            btnGestionTurnos.Name = "btnGestionTurnos";
            btnGestionTurnos.Size = new Size(180, 120);
            btnGestionTurnos.TabIndex = 6;
            btnGestionTurnos.Text = "🕐\r\n\r\nGestión de Turnos\r\n";
            btnGestionTurnos.UseVisualStyleBackColor = false;
            btnGestionTurnos.Click += btnGestionTurnos_Click;
            btnRecepcionarPaciente.BackColor = Color.FromArgb(178, 235, 242);
            btnRecepcionarPaciente.Cursor = Cursors.Hand;
            btnRecepcionarPaciente.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnRecepcionarPaciente.FlatAppearance.BorderSize = 2;
            btnRecepcionarPaciente.FlatStyle = FlatStyle.Flat;
            btnRecepcionarPaciente.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnRecepcionarPaciente.Location = new Point(448, 292);
            btnRecepcionarPaciente.Name = "btnRecepcionarPaciente";
            btnRecepcionarPaciente.Size = new Size(180, 120);
            btnRecepcionarPaciente.TabIndex = 7;
            btnRecepcionarPaciente.Text = "📋✓\r\n\r\nRecepcionar Pacientes";
            btnRecepcionarPaciente.UseVisualStyleBackColor = false;
            btnRecepcionarPaciente.Click += btnRecepcionarPaciente_Click;
            btnAtencionPaciente.BackColor = Color.FromArgb(178, 235, 242);
            btnAtencionPaciente.Cursor = Cursors.Hand;
            btnAtencionPaciente.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnAtencionPaciente.FlatAppearance.BorderSize = 2;
            btnAtencionPaciente.FlatStyle = FlatStyle.Flat;
            btnAtencionPaciente.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            btnAtencionPaciente.Location = new Point(646, 292);
            btnAtencionPaciente.Name = "btnAtencionPaciente";
            btnAtencionPaciente.Size = new Size(180, 120);
            btnAtencionPaciente.TabIndex = 8;
            btnAtencionPaciente.Text = "🏥\r\n\r\nAtención de Pacientes";
            btnAtencionPaciente.UseVisualStyleBackColor = false;
            btnAtencionPaciente.Click += btnAtencionPaciente_Click;
            lblSeccionEstudios.BackColor = Color.FromArgb(0, 150, 136);
            lblSeccionEstudios.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblSeccionEstudios.ForeColor = Color.White;
            lblSeccionEstudios.Location = new Point(30, 440);
            lblSeccionEstudios.Name = "lblSeccionEstudios";
            lblSeccionEstudios.Padding = new Padding(20, 0, 0, 0);
            lblSeccionEstudios.Size = new Size(1203, 40);
            lblSeccionEstudios.TabIndex = 9;
            lblSeccionEstudios.Text = "ESTUDIOS CLÍNICOS";
            lblSeccionEstudios.TextAlign = ContentAlignment.MiddleLeft;
            btnGestionAgendaEstudios.BackColor = Color.FromArgb(178, 235, 242);
            btnGestionAgendaEstudios.Cursor = Cursors.Hand;
            btnGestionAgendaEstudios.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnGestionAgendaEstudios.FlatAppearance.BorderSize = 2;
            btnGestionAgendaEstudios.FlatStyle = FlatStyle.Flat;
            btnGestionAgendaEstudios.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnGestionAgendaEstudios.Location = new Point(50, 500);
            btnGestionAgendaEstudios.Name = "btnGestionAgendaEstudios";
            btnGestionAgendaEstudios.Size = new Size(180, 100);
            btnGestionAgendaEstudios.TabIndex = 10;
            btnGestionAgendaEstudios.Text = "🔬📅\n\nGestión de Agenda\n";
            btnGestionAgendaEstudios.UseVisualStyleBackColor = false;
            btnGestionAgendaEstudios.Click += btnGestionAgendaEstudios_Click;
            btnGestionTurnosEstudios.BackColor = Color.FromArgb(178, 235, 242);
            btnGestionTurnosEstudios.Cursor = Cursors.Hand;
            btnGestionTurnosEstudios.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnGestionTurnosEstudios.FlatAppearance.BorderSize = 2;
            btnGestionTurnosEstudios.FlatStyle = FlatStyle.Flat;
            btnGestionTurnosEstudios.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnGestionTurnosEstudios.Location = new Point(250, 500);
            btnGestionTurnosEstudios.Name = "btnGestionTurnosEstudios";
            btnGestionTurnosEstudios.Size = new Size(180, 100);
            btnGestionTurnosEstudios.TabIndex = 11;
            btnGestionTurnosEstudios.Text = "🔬🕐\n\nGestión de Turnos\n";
            btnGestionTurnosEstudios.UseVisualStyleBackColor = false;
            btnGestionTurnosEstudios.Click += btnGestionTurnosEstudios_Click;
            btnRecepcionarPacienteEstudio.BackColor = Color.FromArgb(178, 235, 242);
            btnRecepcionarPacienteEstudio.Cursor = Cursors.Hand;
            btnRecepcionarPacienteEstudio.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnRecepcionarPacienteEstudio.FlatAppearance.BorderSize = 2;
            btnRecepcionarPacienteEstudio.FlatStyle = FlatStyle.Flat;
            btnRecepcionarPacienteEstudio.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnRecepcionarPacienteEstudio.Location = new Point(450, 500);
            btnRecepcionarPacienteEstudio.Name = "btnRecepcionarPacienteEstudio";
            btnRecepcionarPacienteEstudio.Size = new Size(180, 100);
            btnRecepcionarPacienteEstudio.TabIndex = 12;
            btnRecepcionarPacienteEstudio.Text = "📋✓\n\nRecepcionar";
            btnRecepcionarPacienteEstudio.UseVisualStyleBackColor = false;
            btnRecepcionarPacienteEstudio.Click += btnRecepcionarEstudio_Click;
            btnSolicitudEstudios.BackColor = Color.FromArgb(178, 235, 242);
            btnSolicitudEstudios.Cursor = Cursors.Hand;
            btnSolicitudEstudios.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnSolicitudEstudios.FlatAppearance.BorderSize = 2;
            btnSolicitudEstudios.FlatStyle = FlatStyle.Flat;
            btnSolicitudEstudios.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnSolicitudEstudios.Location = new Point(646, 500);
            btnSolicitudEstudios.Name = "btnSolicitudEstudios";
            btnSolicitudEstudios.Size = new Size(180, 100);
            btnSolicitudEstudios.TabIndex = 13;
            btnSolicitudEstudios.Text = "📝\n\nSolicitar Estudios";
            btnSolicitudEstudios.UseVisualStyleBackColor = false;
            btnSolicitudEstudios.Click += btnSolicitudEstudios_Click;
            btnConfirmacionEstudios.BackColor = Color.FromArgb(178, 235, 242);
            btnConfirmacionEstudios.Cursor = Cursors.Hand;
            btnConfirmacionEstudios.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnConfirmacionEstudios.FlatAppearance.BorderSize = 2;
            btnConfirmacionEstudios.FlatStyle = FlatStyle.Flat;
            btnConfirmacionEstudios.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnConfirmacionEstudios.Location = new Point(848, 500);
            btnConfirmacionEstudios.Name = "btnConfirmacionEstudios";
            btnConfirmacionEstudios.Size = new Size(180, 100);
            btnConfirmacionEstudios.TabIndex = 14;
            btnConfirmacionEstudios.Text = "✅\n\nConfirmar Estudios";
            btnConfirmacionEstudios.UseVisualStyleBackColor = false;
            btnConfirmacionEstudios.Click += btnConfirmacionEstudios_Click;
            btnProcesamientoEstudios.BackColor = Color.FromArgb(178, 235, 242);
            btnProcesamientoEstudios.Cursor = Cursors.Hand;
            btnProcesamientoEstudios.FlatAppearance.BorderColor = Color.FromArgb(0, 150, 136);
            btnProcesamientoEstudios.FlatAppearance.BorderSize = 2;
            btnProcesamientoEstudios.FlatStyle = FlatStyle.Flat;
            btnProcesamientoEstudios.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnProcesamientoEstudios.Location = new Point(1048, 500);
            btnProcesamientoEstudios.Name = "btnProcesamientoEstudios";
            btnProcesamientoEstudios.Size = new Size(180, 100);
            btnProcesamientoEstudios.TabIndex = 15;
            btnProcesamientoEstudios.Text = "⚙️\n\nProcesar Estudios";
            btnProcesamientoEstudios.UseVisualStyleBackColor = false;
            btnProcesamientoEstudios.Click += btnProcesamientoEstudios_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1254, 703);
            Controls.Add(panelContenido);
            Controls.Add(panelHeader);
            Name = "Form1";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Sistema SEPRISE - Consultorios y Estudios Clínicos";
            panelHeader.ResumeLayout(false);
            panelContenido.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion

        private Panel panelHeader;
        private Label lblTitulo;
        private Panel panelContenido;
        private Label lblSeccionComun;
        private Button btnPacientes;
        private Label lblSeccionConsultorios;
        private Button btnGestionMedicos;
        private Button btnGestionAgenda;
        private Button btnGestionTurnos;
        private Button btnRecepcionarPaciente;
        private Button btnAtencionPaciente;
        private Label lblSeccionEstudios;
        private Button btnGestionAgendaEstudios;
        private Button btnGestionTurnosEstudios;
        private Button btnRecepcionarPacienteEstudio;
        private Button btnSolicitudEstudios;
        private Button btnConfirmacionEstudios;
        private Button btnProcesamientoEstudios;
    }
}
